defaults:
  profile: admin
  osystem: ubuntu
  distro_series: jammy
  storage:
    efi_size: 2G
    boot_size: 2G
    root_size: 200G
    data_mount: /data
  networking:
    mode: bond25g
    apply_on_first_boot: true
    predictable_interface_names: true
    predictable_interface_kernel_cmdline: "net.ifnames=1 biosdevname=0"
    bond25g:
      bond_name: bond0
      interfaces:
        - ens12f0np0
        - ens12f1np1
      parameters:
        mode: 802.3ad
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4
    single_nic:
      interface_name: eno4
policy_match_order:
  - h100
  - cpu
  - gpu
  - default
policies:
  default: {}
  gpu:
    match_tags:
      - gpu
      - a800
    storage:
      root_size: 200G
  cpu:
    match_tags:
      - cpu
    networking:
      mode: single_nic
      single_nic:
        interface_name: eno4
    storage:
      root_size: 200G
  h100:
    match_tags:
      - h100
    storage:
      root_size: 300G
